/// @desc
//randomize();
//visitorReady = false;
//mouseOverNewVisitor = false;
visitorChoosen = false;
//justMovedOff = false;
Rating = 3.0;
Score = 0;
visitorModifiers = ds_list_create();
visitorTypes = ds_list_create();
numberOfVisitors = 4;
visitorType = "";
visitorModifier = "";
onChoice2 = false;
onChoice1 = false;
choosenVisitor = 0;
overallSatisfaction = 0.0;
visitorNO = 0.0;
timeOfDay = 6.00;
hourOfDay = 6.00;
startingTime = current_time;
am_pm = "AM";
tutorialVisitorAdded = false;